# breaking-change webhook-based API example
# This is an example of how a normal webhook API works.
# It is meant as a testing operation for the transformation
# between async API calls and webhook based.

POST http://localhost:8082/api/webhook/test
X-Webhook-Url: https://httpbin.org/post
Content-Type: application/json

{
  "data": {
    "a": 1,
    "b": 2
  }
}

###

# Example of transforming a legacy API call into the new webhook-based.
# This transformation is completely transparent to the client to ensure
# backward compatibility with any previous version.

POST http://localhost:8080/api/sync/test
Content-Type: application/json

{
  "data": {
    "a": 1,
    "b": 2
  }
}

###
